apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dx4rl2662-python 
  janus-idp.io/tekton: dx4rl2662-python
  backstage.io/kubernetes-id: dx4rl2662-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dx4rl2662-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml