apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dx4rl2662-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dx4rl2662-python 
  name: dx4rl2662-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dx4rl2662-python 
